### ISSUE TITLE
Can i run MoekadenRoom and Homegateway ( my app using OpenEcho java to receive data from device and send it to server...)

### ISSUE THREAD

**Issue by hoangl-hle** [SonyCSL/MoekadenRoom#3]
I run Homegateway app and it says: "
java.net.BindException: Address already in use: JVM_Bind
        at java.net.DualStackPlainSocketImpl.bind0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketBind(Unknown Source)
        at java.net.AbstractPlainSocketImpl.bind(Unknown Source)
        at java.net.PlainSocketImpl.bind(Unknown Source)
        at java.net.ServerSocket.bind(Unknown Source)
        at java.net.ServerSocket.bind(Unknown Source)
        at com.sonycsl.echo.protocol.EchoTCPProtocol.openTCP(EchoTCPProtocol.java:44)
        at com.sonycsl.echo.EchoSocket.openSocket(EchoSocket.java:54)
        at com.sonycsl.echo.Echo.start(Echo.java:158)
        at main.EchonetController.<init>(EchonetController.java:575)
        at main.MainClass.main(MainClass.java:143)
"
I think the reason is both MoekadenRoom and Homegateway using the same port 3610 to start Echo. What can i do to run both apps on same computer.
Thanks.

**Comment by hoangl-hle** [comment]
@sowd Please help me

**Comment by sowd** [comment]
Hi, Sorry for late reply! (And thank you for reminding

> I think the reason is both MoekadenRoom and Homegateway using the same port 3610 to start Echo. 

You are right.
If you really want to run both in one PC, I recommend to use virtual PC environment such as VirtualBox.

**Comment by hoangl-hle** [comment]
Thank you so much

**Comment by hoangle98** [comment]
Solved
